# Generated by Django 6.0 on 2026-01-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=4)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='FactureExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expedition')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('CARTE', 'Carte bancaire')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamation', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_reclamation', models.CharField(choices=[('RETARD', 'Retard de livraison'), ('QUALITE', 'Qualité de service'), ('FACTURATION', 'Problème de facturation'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('reponse', models.TextField(blank=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.client')),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expedition')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tournee', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chauffeur')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('RETARD', 'Retard'), ('PERTE', 'Perte'), ('ENDOMMAGEMENT', 'Endommagement'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_incident', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('CLOS', 'Clos')], default='OUVERT', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.expedition')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.tournee')),
            ],
        ),
        migrations.CreateModel(
            name='TourneeExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expedition')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='core.tournee')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.CharField(max_length=200)),
                ('statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='core.expedition')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
